'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Reflection
Imports System.Resources
Imports System.Runtime.CompilerServices
Imports System.Runtime.InteropServices
<Assembly: AssemblyCompany("K4GDW Software"), _
 Assembly: AssemblyCopyright("Copyright © K4GDW 2011,2012,2013"), _
 Assembly: AssemblyTrademark("K4GDW"), _
 Assembly: AssemblyVersion("4.2"), _
 Assembly: AssemblyFileVersion("4.2.1.2"), _
 Assembly: AssemblyInformationalVersion("4.2.1.2")> 

